In [ ]:
import numpy as np
import re

In [ ]:
# Creating Domain Question and Answers

database = [
    ("What are the courses run by JMI?", "JMI runs the courses of BTech, MTech, MBA, etc."),
    ("Where is JMI located?", "JMI is located in Jamia Nagar, New Delhi.")
]

In [ ]:
# Create Vocabulary

vocab = set()
for ques, ans in database:
  words = re.findall(r"\w+", ques) + re.findall(r"\w+", ans)
  for word in words:
    vocab.add(word.lower())
vocab

{'are',
 'btech',
 'by',
 'courses',
 'delhi',
 'etc',
 'in',
 'is',
 'jamia',
 'jmi',
 'located',
 'mba',
 'mtech',
 'nagar',
 'new',
 'of',
 'run',
 'runs',
 'the',
 'what',
 'where'}

In [ ]:
def getBOWVector(sent, vocab):
  count_dict = {v: 0 for v in vocab}

  for word in re.findall(r"\w+", sent):
    if word.lower() in count_dict:
      count_dict[word.lower()] += 1

  bow_vector = np.array([v for k,v in count_dict.items()])
  return bow_vector

def cosine_sim(a, b):
  return np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b) + 1e-10)

In [ ]:
def get_answer(question, database):
  # Create BOW vectors for database questions
  questions_bow = []
  for ques, _ in database:
    questions_bow.append(getBOWVector(ques, vocab))

  cur_q_bow = getBOWVector(question, vocab)
  print(cur_q_bow)
  # Compute cosine similiarty with existing questions in database
  similarities = []
  for ques_bow in questions_bow:
    similarities.append(cosine_sim(cur_q_bow, ques_bow))

  # return answer for question with max similarity
  return database[np.argmax(similarities)][1]

In [ ]:
print("Welcome to Simple QA chatbot")
print("Enter 'exit' to end session")
while True:
  new_question = str(input("\nQuestion: "))
  if new_question == "exit":
    print("Goodbye :)")
    break
  print("Answer:",get_answer(new_question, database))

Welcome to Simple QA chatbot
Enter 'exit' to end session

Question: Which course is best?
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
Answer: JMI is located in Jamia Nagar, New Delhi.

Question: Which couses is best?
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
Answer: JMI is located in Jamia Nagar, New Delhi.

Question: Which courses is best?
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0]
Answer: JMI is located in Jamia Nagar, New Delhi.

Question: Which courses in JMI?
[0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0]
Answer: JMI runs the courses of BTech, MTech, MBA, etc.
